\c military_base;

ALTER TABLE soldiers ADD CONSTRAINT U_ID UNIQUE (id), ADD CONSTRAINT P_ID PRIMARY KEY (id);
ALTER TABLE soldiers ALTER COLUMN first_name SET NOT NULL;
ALTER TABLE soldiers ALTER COLUMN last_name SET NOT NULL;
ALTER TABLE soldiers ALTER COLUMN rank SET NOT NULL;
ALTER TABLE soldiers ALTER COLUMN age SET NOT NULL;
ALTER TABLE soldiers ALTER COLUMN salary SET NOT NULL;
ALTER TABLE soldiers ALTER COLUMN arrival_date SET NOT NULL;

ALTER TABLE soldiers ADD CONSTRAINT CH_AGES CHECK (age >= 18);
ALTER TABLE soldiers ADD CONSTRAINT CH_SALARY CHECK (salary > 500);

ALTER TABLE weapons ADD CONSTRAINT U_WID UNIQUE (id), ADD CONSTRAINT P_WID PRIMARY KEY (id);
ALTER TABLE weapons ALTER COLUMN name SET NOT NULL;
ALTER TABLE weapons ALTER COLUMN classification SET NOT NULL;
ALTER TABLE weapons ALTER COLUMN caliber SET NOT NULL;
ALTER TABLE weapons ALTER COLUMN status SET NOT NULL;
ALTER TABLE weapons ALTER COLUMN produced SET NOT NULL;
ALTER TABLE weapons ALTER COLUMN last_check SET NOT NULL;

ALTER TABLE weapons ADD CONSTRAINT F_AWID FOREIGN KEY (attached_soldier_id) REFERENCES soldiers(id), ADD CONSTRAINT U_AWID UNIQUE (attached_soldier_id);

ALTER TABLE ammunition ADD CONSTRAINT U_AMID UNIQUE (id), ADD CONSTRAINT P_AMID PRIMARY KEY (id);
ALTER TABLE ammunition ALTER COLUMN name SET NOT NULL;
ALTER TABLE ammunition ALTER COLUMN caliber SET NOT NULL;
ALTER TABLE ammunition ALTER COLUMN type SET NOT NULL;
ALTER TABLE ammunition ALTER COLUMN quantity SET NOT NULL;
ALTER TABLE ammunition ALTER COLUMN status SET NOT NULL;

ALTER TABLE ammunition ADD CONSTRAINT CH_AMMO CHECK (quantity >= 0);
ALTER TABLE ammunition ADD CONSTRAINT F_AAID FOREIGN KEY (attached_soldier_id) REFERENCES soldiers(id), ADD CONSTRAINT U_AAID UNIQUE (attached_soldier_id);

ALTER TABLE vehicles ADD CONSTRAINT U_VID UNIQUE (id), ADD CONSTRAINT P_VID PRIMARY KEY (id);
ALTER TABLE vehicles ALTER COLUMN name SET NOT NULL;
ALTER TABLE vehicles ALTER COLUMN status SET NOT NULL;
ALTER TABLE vehicles ALTER COLUMN capacity SET NOT NULL;
ALTER TABLE vehicles ALTER COLUMN armored SET NOT NULL;
ALTER TABLE vehicles ALTER COLUMN produced SET NOT NULL;

ALTER TABLE vehicles ADD CONSTRAINT CH_CAPACITY CHECK (capacity > 0);
ALTER TABLE vehicles ADD CONSTRAINT F_AVID FOREIGN KEY (attached_soldier_id) REFERENCES soldiers(id), ADD CONSTRAINT U_AVID UNIQUE (attached_soldier_id);

